name: docs-deploy

on:
  push:
    branches: ['master', 'main']

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.x
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: ls-lint
        run: pnpm ls-lint
      - name: Test
        run: pnpm test
      - name: Build
        run: pnpm build
      - name: Docs build
        run: pnpm docs-build
      - name: Docs Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./docs/dist
